server{
	listen 80;
	server_name company.local;
	return 301 https://$host$request_uri;
	}
server{
	listen 443 ssl;
	server_name company.local;

	ssl_certificate /home/osboxes/server.crt;
	ssl_certificate_key /home/osboxes/server.key;

	location / {
	proxy_pass http://localhost:8080;
	proxy_pass_header Host $host;
	proxy_pass_header X-Real-IP $remote_addr;
	}
}